# Generated by Django 3.1.7 on 2021-03-22 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purbeurre', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='name',
            name='category',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='purbeurre.category_product'),
        ),
        migrations.AlterField(
            model_name='name',
            name='name_product',
            field=models.CharField(max_length=250, primary_key=True, serialize=False, unique=True),
        ),
    ]
