# Generated by Django 3.1.7 on 2021-03-22 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purbeurre', '0003_auto_20210322_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='name',
            name='category',
        ),
    ]
