language: python
python:
  - '3.8.3'

# safelist
branches:
  only:
    - staging

before_install:
  - python -m pip install --upgrade pip

install:
  - pip install -r requirements.txt

env: DJANGO_SETTINGS_MODULE="DashbordDevise.settings.travis"

services:
  - postgresql

script:
  - python manage.py test
