language: python
python:
  - '3.8.3'

# safelist
branches:
  only:
    - staging

before_install:
  - python -m pip install --upgrade pip

install:
  - pip install -r requirements.txt

env: DJANGO_SETTINGS_MODULE="DashbordDevise.settings.travis"

services:
  - postgresql

before_script:
  - wget https://chromedriver.storage.googleapis.com/83.0.4103.39/chromedriver_linux64.zip

  - unzip chromedriver_linux64.zip -d /home/travis/build/Frantz680/P8_Nutella/accounts/tests/

  - psql -c 'create database purbeurre;' -U postgres

script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py test
